// packages/app-react/components/Arrow.tsx
import styled from "styled-components"

export default function Arrow() {
  return (
    <Wrapper>
      <ArrowBody />
      <ArrowHead />
    </Wrapper>
  )
}
const Wrapper = styled.div`
  display: flex;
  width: 100%;
  align-items: center;
`
const ArrowBody = styled.div`
  border: 0.0625rem dashed #d8d8dc;
  width: 100%;
`
export const ARROW_HEAD_WIDTH = "0.75rem"
const ArrowHead = styled.div`
  border-top: calc(${ARROW_HEAD_WIDTH} / 2) solid transparent;
  border-bottom: calc(${ARROW_HEAD_WIDTH} / 2) solid transparent;
  border-left: ${ARROW_HEAD_WIDTH} solid #d8d8dc;
  flex: none;
`

// packages/app-vue/components/Arrow.vue
<template>
  <div class="wrapper">
    <div class="arrow-body" />
    <div class="arrow-head" />
  </div>
</template>

<style scoped>
.wrapper {
  display: flex;
  width: 100%;
  align-items: center;
}
.arrow-body {
  border: 0.0625rem dashed #d8d8dc;
  width: 100%;
}
.arrow-head {
  border-top: calc(0.75rem / 2) solid transparent;
  border-bottom: calc(0.75rem / 2) solid transparent;
  border-left: 0.75rem solid #d8d8dc;
  flex: none;
}
</style>
